DJGPP = i686-pc-msdosdjgpp-

CC = $(DJGPP)gcc

STRIP = $(DJGPP)strip

SIZE = $(DJGPP)size

CFLAGS += \
	-DMICROPY_NLR_SETJMP \
	-Dtgamma=gamma \
	-DMICROPY_EMIT_X86=0 \
	-DMICROPY_NO_ALLOCA=1 \

PROG = upython

MICROPY_PY_SOCKET = 0
MICROPY_PY_FFI = 0
MICROPY_PY_JNI = 0
MICROPY_PY_BTREE = 0
MICROPY_PY_THREAD = 0
MICROPY_PY_USSL = 0

MICROPY_FORCE_32BIT = 1
