.. comment: This file is intended for global "replace" definitions.

.. |see_cpython| replace:: See CPython documentation:

.. |see_cpython_module| replace::

    *This module implements a subset of the corresponding* `CPython` *module,
    as described below. For more information, refer to the original
    CPython documentation:*

.. |machine_ids| replace::

    See the port-specific guide for machine IDs: :ref:`pyboard
    <machine_pyboard>`, :ref:`STM32 <machine_stm32>`, :ref:`ESP32
    <machine_esp32>`, :ref:`ESP8266 <machine_esp8266>`, :ref:`NRF5x
    <machine_nrf>`.

.. |availability_portable| replace:: Availability: **Portable**.
.. |availability_portable_wip| replace:: Availability: **Portable** (Note: WIP, not supported on all ports yet).

.. |availability_cc3200_esp32_esp8266_nrf_stm32| replace:: Availability: STM32/pyboard, ESP32, ESP8266, WiPy (CC3200), NRF5x.
.. |availability_cc3200_esp32| replace:: Availability: ESP32, WiPy (CC3200).
.. |availability_cc3200_esp_nrf| replace:: Availability: ESP32, ESP8266, WiPy (CC3200), NRF5x.
.. |availability_cc3200| replace:: Availability: WiPy (CC3200).
.. |availability_esp32_esp8266_stm32| replace:: Availability: STM32/pyboard, ESP32, ESP8266.
.. |availability_esp32_stm32| replace:: Availability: STM32/pyboard, ESP32.
.. |availability_esp32| replace:: Availability: ESP32.
.. |availability_esp8266| replace:: Availability: ESP8266.
.. |availability_esp| replace:: Availability: ESP32, ESP8266.
.. |availability_stm32| replace:: Availability: STM32/pyboard.

.. |availability_deprecated| replace:: Availability: **Deprecated**.
.. |availability_todo| replace:: Availability: It's complicated.
