#ifndef MICROPY_INCLUDED_QUOKKA_CONFIG_BOARD_H
#define MICROPY_INCLUDED_QUOKKA_CONFIG_BOARD_H

#include "../PYBLITEV10/mpconfigboard.h"

#undef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME       "PYBLITEv1.0-QUOKKA"

#endif
